package com.lxiaow.mapper;

import com.lxiaow.entity.Admin;
import org.springframework.stereotype.Repository;


@Repository
public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer admAdminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    Admin selectByPrimaryKey(Integer admAdminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Admin record);
}