package com.lxiaow.mapper;

import com.lxiaow.entity.admin;
import org.springframework.stereotype.Repository;


@Repository
public interface adminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer admAdminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int insert(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int insertSelective(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    admin selectByPrimaryKey(Integer admAdminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ADMIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(admin record);
}