package com.lxiaow.entity;

import java.util.Date;

public class admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_ADMIN_ID
     *
     * @mbg.generated
     */
    private Integer admAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_ADMIN_NAME
     *
     * @mbg.generated
     */
    private String admAdminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_ADMIN_PASSWORD
     *
     * @mbg.generated
     */
    private String admAdminPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_IS_SUPER_ADMIN
     *
     * @mbg.generated
     */
    private Integer admIsSuperAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_STATUS
     *
     * @mbg.generated
     */
    private Integer admStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_ERROR_COUNT
     *
     * @mbg.generated
     */
    private Integer admErrorCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_LAST_LOGIN_TIME
     *
     * @mbg.generated
     */
    private Date admLastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_PROVINCE
     *
     * @mbg.generated
     */
    private String admProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_ADMIN_PHONE
     *
     * @mbg.generated
     */
    private String admAdminPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.ADM_ADMIN_EMAIL
     *
     * @mbg.generated
     */
    private String admAdminEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ADMIN.GROUP_ID
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_ADMIN_ID
     *
     * @return the value of M_ADMIN.ADM_ADMIN_ID
     *
     * @mbg.generated
     */
    public Integer getAdmAdminId() {
        return admAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_ADMIN_ID
     *
     * @param admAdminId the value for M_ADMIN.ADM_ADMIN_ID
     *
     * @mbg.generated
     */
    public void setAdmAdminId(Integer admAdminId) {
        this.admAdminId = admAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_ADMIN_NAME
     *
     * @return the value of M_ADMIN.ADM_ADMIN_NAME
     *
     * @mbg.generated
     */
    public String getAdmAdminName() {
        return admAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_ADMIN_NAME
     *
     * @param admAdminName the value for M_ADMIN.ADM_ADMIN_NAME
     *
     * @mbg.generated
     */
    public void setAdmAdminName(String admAdminName) {
        this.admAdminName = admAdminName == null ? null : admAdminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_ADMIN_PASSWORD
     *
     * @return the value of M_ADMIN.ADM_ADMIN_PASSWORD
     *
     * @mbg.generated
     */
    public String getAdmAdminPassword() {
        return admAdminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_ADMIN_PASSWORD
     *
     * @param admAdminPassword the value for M_ADMIN.ADM_ADMIN_PASSWORD
     *
     * @mbg.generated
     */
    public void setAdmAdminPassword(String admAdminPassword) {
        this.admAdminPassword = admAdminPassword == null ? null : admAdminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_IS_SUPER_ADMIN
     *
     * @return the value of M_ADMIN.ADM_IS_SUPER_ADMIN
     *
     * @mbg.generated
     */
    public Integer getAdmIsSuperAdmin() {
        return admIsSuperAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_IS_SUPER_ADMIN
     *
     * @param admIsSuperAdmin the value for M_ADMIN.ADM_IS_SUPER_ADMIN
     *
     * @mbg.generated
     */
    public void setAdmIsSuperAdmin(Integer admIsSuperAdmin) {
        this.admIsSuperAdmin = admIsSuperAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_STATUS
     *
     * @return the value of M_ADMIN.ADM_STATUS
     *
     * @mbg.generated
     */
    public Integer getAdmStatus() {
        return admStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_STATUS
     *
     * @param admStatus the value for M_ADMIN.ADM_STATUS
     *
     * @mbg.generated
     */
    public void setAdmStatus(Integer admStatus) {
        this.admStatus = admStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_ERROR_COUNT
     *
     * @return the value of M_ADMIN.ADM_ERROR_COUNT
     *
     * @mbg.generated
     */
    public Integer getAdmErrorCount() {
        return admErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_ERROR_COUNT
     *
     * @param admErrorCount the value for M_ADMIN.ADM_ERROR_COUNT
     *
     * @mbg.generated
     */
    public void setAdmErrorCount(Integer admErrorCount) {
        this.admErrorCount = admErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_LAST_LOGIN_TIME
     *
     * @return the value of M_ADMIN.ADM_LAST_LOGIN_TIME
     *
     * @mbg.generated
     */
    public Date getAdmLastLoginTime() {
        return admLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_LAST_LOGIN_TIME
     *
     * @param admLastLoginTime the value for M_ADMIN.ADM_LAST_LOGIN_TIME
     *
     * @mbg.generated
     */
    public void setAdmLastLoginTime(Date admLastLoginTime) {
        this.admLastLoginTime = admLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_PROVINCE
     *
     * @return the value of M_ADMIN.ADM_PROVINCE
     *
     * @mbg.generated
     */
    public String getAdmProvince() {
        return admProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_PROVINCE
     *
     * @param admProvince the value for M_ADMIN.ADM_PROVINCE
     *
     * @mbg.generated
     */
    public void setAdmProvince(String admProvince) {
        this.admProvince = admProvince == null ? null : admProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_ADMIN_PHONE
     *
     * @return the value of M_ADMIN.ADM_ADMIN_PHONE
     *
     * @mbg.generated
     */
    public String getAdmAdminPhone() {
        return admAdminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_ADMIN_PHONE
     *
     * @param admAdminPhone the value for M_ADMIN.ADM_ADMIN_PHONE
     *
     * @mbg.generated
     */
    public void setAdmAdminPhone(String admAdminPhone) {
        this.admAdminPhone = admAdminPhone == null ? null : admAdminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.ADM_ADMIN_EMAIL
     *
     * @return the value of M_ADMIN.ADM_ADMIN_EMAIL
     *
     * @mbg.generated
     */
    public String getAdmAdminEmail() {
        return admAdminEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.ADM_ADMIN_EMAIL
     *
     * @param admAdminEmail the value for M_ADMIN.ADM_ADMIN_EMAIL
     *
     * @mbg.generated
     */
    public void setAdmAdminEmail(String admAdminEmail) {
        this.admAdminEmail = admAdminEmail == null ? null : admAdminEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ADMIN.GROUP_ID
     *
     * @return the value of M_ADMIN.GROUP_ID
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ADMIN.GROUP_ID
     *
     * @param groupId the value for M_ADMIN.GROUP_ID
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    @Override
    public String toString() {
        return "admin{" +
                "admAdminId=" + admAdminId +
                ", admAdminName='" + admAdminName + '\'' +
                ", admAdminPassword='" + admAdminPassword + '\'' +
                ", admIsSuperAdmin=" + admIsSuperAdmin +
                ", admStatus=" + admStatus +
                ", admErrorCount=" + admErrorCount +
                ", admLastLoginTime=" + admLastLoginTime +
                ", admProvince='" + admProvince + '\'' +
                ", admAdminPhone='" + admAdminPhone + '\'' +
                ", admAdminEmail='" + admAdminEmail + '\'' +
                ", groupId=" + groupId +
                '}';
    }
}