server:
  port: 8080

spring:
  datasource:
    username: root
    password: dragon
    url: jdbc:mysql://101.132.165.149:3306/bootTest?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true #默认支持文件上传
      location: #默认保存位置
      max-file-size: 20MB #最大支持文件大小
      max-request-size: 40MB #最大支持总文件大小
      resolve-lazily: true
      file-size-threshold: 0 #支持文件写入磁盘


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lxiaow.springboot_mybatis

