server:
  port: 8080

spring:
  datasource:
    username: root
    password: dragon
    url: jdbc:mysql://101.132.165.149:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lxiaow.springboot_mybatis

